; Apio project configuration file.
; See https://fpgawars.github.io/apio/docs/project-file for details.

[env:default]
board = upduino31
; top-module = lab2_cj_display
; constraint-file = display.pcf
top-module = lab2_cj_keypad
constraint-file = keypad.pcf